const games = [
  "1v1.LoL.html",
  "8 Ball Pool.html",
  "A Bite at Freddy's.html",
  "A Difficult Game About Climbing.html",
  "Amaze.html",
  "Amanda the Adventurer.html",
  "Angry Birds.html",
  "Backrooms.html",
  "Bad Parenting 1.html",
  "baldi.html",
  "Basket Bros.html",
  "Bendy and the Ink Machine.html",
  "bitlife.html",
  "Blade Ball.html",
  "Bowmasters.html",
  "Candy Crush.html",
  "Cluster Rush.html",
  "Color Match.html",
  "Color Water Sort 3D.html",
  "Count Masters_ Stickman.html",
  "crossy road.html",
  "Cut the Rope.html",
  "Drift Boss.html",
  "Five Nights at Epstein's.html",
  "Five Nights at Freddy's.html",
  "Five Nights at Freddy's 2.html",
  "Five Nights at Freddy's 3.html",
  "Five Nights at Freddy's 4.html",
  "Five Nights at Freddy's_ Pizza Simulator.html",
  "Five Nights at Freddy's_ Sister Location.html",
  "Five Nights at Freddy's_ Ultimate Custom Night.html",
  "Five Nights at Freddy's_ World.html",
  "Flappy Bird.html",
  "Friday Night Funkin.html",
  "Geometry Dash Lite.html",
  "Getting Over It with Bennett Foddy.html",
  "Going Balls.html",
  "Gorilla Tag.html",
  "Granny.html",
  "Half Life.html",
  "Happy Wheels.html",
  "Hill Climb Racing Lite.html",
  "Jelly Drift.html",
  "Jelly Mario.html",
  "Jetpack Joyride.html",
  "Melon Playground.html",
  "Minecraft 1.12.2.html",
  "Minecraft 1.21.4.html",
  "Money Run 3D.html",
  "Monster Tracks.html",
  "Moto X3M.html",
  "OvO.html",
  "OvO 2.html",
  "OvO 3 Dimensions.html",
  "Parappa The Rapper.html",
  "People Playground.html",
  "Pou.html",
  "R.E.P.O.html",
  "Raldi's Crackhouse.html",
  "RE_RUN.html",
  "Red Ball_4.html",
  "Retro Bowl.html",
  "run1.html",
  "run2.html",
  "run3.html",
  "Schoolboy Runaway.html",
  "Slope.html",
  "Solar Smash.html",
  "Stacky Dash.html",
  "Steal A Brainrot.html",
  "Stickman Hook.html",
  "Subway Surfers_ St. Petersburg.html",
  "Super Mario 64.html",
  "Tattletail.html",
  "Temple Run 2.html",
  "That's Not My Neighbor.html",
  "Tiny Fishing.html",
  "Toy Rider.html",
  "Twerk Race 3D.html",
  "ULTRAKILL.html",
  "Yandere Simulator.html"
];
