const games = [
  "1v1.LoL.html",
  "Amaze.html",
  "Angry Birds.html",
  "A Difficult Game About Climbing.html",
  "baldi.html",
  "bitlife.html",
  "Blade Ball.html",
  "Cluster Rush.html",
  "Color Match.html",
  "Count Masters_ Stickman Games.html",
  "crossy road.html",
  "Five Nights at Freddy's 4.html",
  "Five Nights at Freddy's_ Ultimate Custom Night.html",
  "Five Nights at Freddy's.html",
  "Five Nights at Epstein's.html",
  "Flappy Bird.html",
  "Going Balls.html",
  "Getting Over It with Bennett Foddy.html",
  "Gorilla Tag.html",
  "Granny.html",
  "Geometry Dash Lite.html",
  "Hill Climb Racing Lite.html",
  "Half Life.html",
  "Jelly Drift.html",
  "Melon Playground.html",
  "Minecraft 1.12.2.html",
  "Minecraft 1.21.4.html",
  "Money Run 3D.html",
  "Moto X3M.html",
  "People Playground.html",
  "Pou.html",
  "Red Ball_4.html",
  "run1.html",
  "run2.html",
  "run3.html",
  "RE_RUN.html",
  "R.E.P.O.html",
  "Slope.html",
  "Stacky Dash.html",
  "Steal A Brainrot.html",
  "Subway Surfers_ St. Petersburg.html",
  "Super Mario 64.html",
  "Schoolboy Runaway.html"
];



